ALTER TABLE routes
  DROP CONSTRAINT IF EXISTS check_route_type_valid;

ALTER TABLE routes
  ADD CONSTRAINT check_route_type_valid
  CHECK (route_type IN (
    'TRAM', 'SUBWAY', 'RAIL', 'BUS', 'FERRY', 'CABLE_TRAM', 'AERIAL_LIFT', 'FUNICULAR', 'TROLLEYBUS', 'MONORAIL',
    'RAILWAY_SERVICE', 'HIGH_SPEED_RAIL_SERVICE', 'LONG_DISTANCE_TRAINS', 'INTER_REGIONAL_RAIL_SERVICE',
    'CAR_TRANSPORT_RAIL_SERVICE', 'SLEEPER_RAIL_SERVICE', 'REGIONAL_RAIL_SERVICE', 'TOURIST_RAILWAY_SERVICE',
    'RAIL_SHUTTLE_WITHIN_COMPLEX', 'SUBURBAN_RAILWAY', 'REPLACEMENT_RAIL_SERVICE', 'SPECIAL_RAIL_SERVICE',
    'LORRY_TRANSPORT_RAIL_SERVICE', 'ALL_RAIL_SERVICES', 'CROSS_COUNTRY_RAIL_SERVICE',
    'VEHICLE_TRANSPORT_RAIL_SERVICE', 'RACK_AND_PINION_RAILWAY', 'ADDITIONAL_RAIL_SERVICE', 'COACH_SERVICE',
    'INTERNATIONAL_COACH_SERVICE', 'NATIONAL_COACH_SERVICE', 'SHUTTLE_COACH_SERVICE', 'REGIONAL_COACH_SERVICE',
    'SPECIAL_COACH_SERVICE', 'SIGHTSEEING_COACH_SERVICE', 'TOURIST_COACH_SERVICE', 'COMMUTER_COACH_SERVICE',
    'ALL_COACH_SERVICES', 'URBAN_RAILWAY_SERVICE', 'METRO_SERVICE', 'UNDERGROUND_SERVICE',
    'URBAN_RAILWAY_SERVICE_403', 'ALL_URBAN_RAILWAY_SERVICES', 'MONORAIL_SERVICE', 'BUS_SERVICE',
    'REGIONAL_BUS_SERVICE', 'EXPRESS_BUS_SERVICE', 'STOPPING_BUS_SERVICE', 'LOCAL_BUS_SERVICE',
    'NIGHT_BUS_SERVICE', 'POST_BUS_SERVICE', 'SPECIAL_NEEDS_BUS', 'MOBILITY_BUS_SERVICE',
    'MOBILITY_BUS_FOR_REGISTERED_DISABLED', 'SIGHTSEEING_BUS', 'SHUTTLE_BUS', 'SCHOOL_BUS',
    'SCHOOL_AND_PUBLIC_SERVICE_BUS', 'RAIL_REPLACEMENT_BUS_SERVICE', 'DEMAND_AND_RESPONSE_BUS_SERVICE',
    'ALL_BUS_SERVICES', 'TROLLEYBUS_SERVICE', 'TRAM_SERVICE', 'CITY_TRAM_SERVICE', 'LOCAL_TRAM_SERVICE',
    'REGIONAL_TRAM_SERVICE', 'SIGHTSEEING_TRAM_SERVICE', 'SHUTTLE_TRAM_SERVICE', 'ALL_TRAM_SERVICES',
    'WATER_TRANSPORT_SERVICE', 'AIR_SERVICE', 'FERRY_SERVICE', 'AERIAL_LIFT_SERVICE', 'TELECABIN_SERVICE',
    'CABLE_CAR_SERVICE', 'ELEVATOR_SERVICE', 'CHAIR_LIFT_SERVICE', 'DRAG_LIFT_SERVICE', 'SMALL_TELECABIN_SERVICE',
    'ALL_TELECABIN_SERVICES', 'FUNICULAR_SERVICE', 'TAXI_SERVICE', 'COMMUNAL_TAXI_SERVICE', 'WATER_TAXI_SERVICE',
    'RAIL_TAXI_SERVICE', 'BIKE_TAXI_SERVICE', 'LICENSED_TAXI_SERVICE', 'PRIVATE_HIRE_SERVICE_VEHICLE',
    'ALL_TAXI_SERVICES', 'MISCELLANEOUS_SERVICE', 'HORSE_DRAWN_CARRIAGE'
  ));

COMMENT ON COLUMN routes.route_type IS 'GTFS route_type as VARCHAR with check constraint for valid values';
